merge:
  whitelist:
    # a PR must have these labels set
    labels: ["automerge", "dependencies"]
  blacklist:
    # a PR may not have these labels set
    labels: ["wip"]
  # merge method, see https://help.github.com/en/articles/about-merge-methods-on-github
  # one of: merge, squash, rebase
  method: squash
  # status checks required in addition to the ones defined in GitHub Branch Protection Rules
  required_statuses:
    - "test1"
    - "test2"
  delete_after_merge: true
